import { motion } from 'motion/react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import { ShieldCheck, Globe, Satellite, FileDown, AlertCircle, HelpCircle, Check, RefreshCw as Sync } from 'lucide-react';
import { cn } from '@/src/lib/utils';
import { useEffect, useState } from "react";
import { getAllVerifications } from "@/src/services/firestore";
import { jsPDF } from "jspdf";
import {
  CircularProgressbar,
  buildStyles
} from "react-circular-progressbar";

import "react-circular-progressbar/dist/styles.css";


export default function InsightsPage() {

  const [scans, setScans] = useState<any[]>([]);

  const totalScans = scans.length;

const factCount = scans.filter(
  (scan) => scan.verdict === "FACT"
).length;

const capCount = scans.filter(
  (scan) => scan.verdict === "CAP"
).length;

const susCount = scans.filter(
  (scan) => scan.verdict === "SUS"
).length;

const averageTrust =
  totalScans > 0
    ? Math.round(
        scans.reduce(
          (sum, scan) => sum + (scan.trustScore || 0),
          0
        ) / totalScans
      )
    : 0;

const maxMetric = Math.max(
  totalScans,
  factCount,
  capCount,
  1
);
  const data = [
  {
    label: "FACT",
    value: factCount
  },
  {
    label: "CAP",
    value: capCount
  },
  {
    label: "SUS",
    value: susCount
  }
];

   useEffect(() => {
  const loadScans = async () => {
    const data = await getAllVerifications();
    setScans(data);
  };

  loadScans();
}, []);

const downloadAuditReport = () => {
const doc = new jsPDF();

const pageWidth = doc.internal.pageSize.getWidth();

// Header
doc.setFontSize(24);
doc.setFont("helvetica", "bold");
doc.text("SPORTSNAP AI", pageWidth / 2, 20, { align: "center" });

doc.setFontSize(16);
doc.setFont("helvetica", "normal");
doc.text(
"Verification Audit Report",
pageWidth / 2,
30,
{ align: "center" }
);

// Divider
doc.line(20, 38, 190, 38);

// Metadata
doc.setFontSize(11);
doc.text(
`Generated: ${new Date().toLocaleString()}`,
20,
50
);

// Summary Section
doc.setFontSize(15);
doc.setFont("helvetica", "bold");
doc.text("EXECUTIVE SUMMARY", 20, 70);

doc.line(20, 73, 90, 73);

doc.setFont("helvetica", "normal");
doc.setFontSize(12);

doc.text(`Total Verifications: ${totalScans}`, 25, 85);
doc.text(`FACT Count: ${factCount}`, 25, 95);
doc.text(`CAP Count: ${capCount}`, 25, 105);
doc.text(`SUS Count: ${susCount}`, 25, 115);
doc.text(`Average Trust Score: ${averageTrust}%`, 25, 125);

// History Section
doc.setFont("helvetica", "bold");
doc.setFontSize(15);
doc.text("RECENT VERIFICATIONS", 20, 150);

doc.line(20, 153, 105, 153);

let y = 165;

scans
.slice(0, 10)
.forEach((scan, index) => {
if (y > 260) {
doc.addPage();
y = 20;
}

  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);

  doc.text(
    `${index + 1}. ${scan.claim}`,
    25,
    y
  );

  y += 8;

  doc.setFont("helvetica", "normal");

  doc.text(
    `Verdict: ${scan.verdict}`,
    35,
    y
  );

  y += 7;

  doc.text(
    `Date: ${new Date(scan.createdAt).toLocaleDateString()}`,
    35,
    y
  );

  y += 12;
});

// Footer
doc.setFontSize(10);
doc.setTextColor(120);

doc.text(
"Generated by SportSnap AI Verification Platform",
pageWidth / 2,
285,
{ align: "center" }
);

doc.save("SportSnap-Audit-Report.pdf");
};


  return (
    <div className="flex flex-col items-center">
      <motion.div 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        className="max-w-[1440px] px-8 py-12 md:py-16 w-full"
      >
        <div className="mb-16">
          <h1 className="font-display text-7xl text-white mb-4 tracking-tight font-bold">Trust Report Dashboard</h1>
          <p className="text-slate-400 text-xl font-medium max-w-2xl leading-relaxed">
            Real-time media verification engine. Processing satellite, metadata, and pixel-level integrity for global sports assets.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-12 gap-8 mb-12">
          {/* Main Chart */}
          <div className="col-span-12 lg:col-span-8 glass-card rounded-[2.5rem] p-10 flex flex-col">
            <div className="flex justify-between items-start mb-12">
              <div>
                <h3 className="font-display text-3xl font-bold text-white mb-2">Authenticity Breakdown</h3>
                <p className="text-slate-500 font-medium">Verification results from your archive</p>
              </div>
              <div className="flex items-center gap-3 px-5 py-2 bg-accent-green/10 border border-accent-green/20 rounded-full">
                <span className="w-2.5 h-2.5 rounded-full bg-accent-green animate-pulse"></span>
                <span className="text-accent-green font-black tracking-widest text-[10px] uppercase">{totalScans} VERIFICATIONS</span>
              </div>
            </div>

            <div className="h-[350px] w-full">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={data} margin={{ top: 0, right: 0, left: -20, bottom: 30 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#ffffff05" vertical={false} />
                  <XAxis 
                    dataKey="label" 
                    stroke="#475569" 
                    tick={{ fill: '#475569', fontWeight: 700, fontSize: 12 }} 
                    axisLine={false}
                    tickLine={false}
                    dy={10}
                  />
                  <YAxis hide />
                  <Tooltip 
                    cursor={false}
                    content={({ active, payload }) => {
                      if (active && payload && payload.length) {
                        return (
                          <div className="glass-card p-4 rounded-xl border-accent-blue/30 shadow-2xl">
  <p className="text-white font-black text-[10px] mb-1 uppercase tracking-widest">
    {payload[0].payload.label}
  </p>
  <p className="text-accent-blue font-display text-2xl font-bold">
    {payload[0].value}
  </p>
</div>
                        );
                      }
                      return null;
                    }}
                  />
                  <Bar dataKey="value" radius={[12, 12, 0, 0]} barSize={100} activeBar={{
    stroke: "#ffffff",
    strokeWidth: 1
  }}>
                    {data.map((entry, index) => (
  <Cell

className={cn(
  "transition-all duration-300 cursor-pointer hover:opacity-100"
)}
    key={`cell-${index}`}
    fill={
      entry.label === "FACT"
        ? "#10B981"
        : entry.label === "CAP"
        ? "#EF4444"
        : "#F59E0B"
    }
  />
))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            </div>
            
                      </div>

          {/* Credibility Scores */}
          <div className="col-span-12 lg:col-span-4 glass-card rounded-[2.5rem] p-10 flex flex-col justify-between">
            <h3 className="font-display text-3xl font-bold text-white mb-10 tracking-tight">Verification Summary</h3>
            
            <div className="space-y-10 flex-grow">
              {[
  {
    icon: ShieldCheck,
    label: "Total Verifications",
    score: totalScans,
    color: "bg-accent-blue"
  },
  {
    icon: Check,
    label: "FACT Count",
    score: factCount,
    color: "bg-accent-green"
  },
  {
    icon: AlertCircle,
    label: "CAP Count",
    score: capCount,
    color: "bg-red-500"
  },
   {
    icon: HelpCircle,
    label: "SUS Count",
    score: susCount,
    color: "bg-yellow-500"
  }

].map((item, index) => (
                <div key={index} className="space-y-4">
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-4 text-slate-200">
                      <item.icon className={cn("w-6 h-6", item.color === 'bg-accent-blue'
  ? 'text-accent-blue'
  : item.color === 'bg-red-500'
  ? 'text-red-500'
  : item.color === 'bg-yellow-500'
  ? 'text-yellow-400'
  : 'text-accent-green')} />
                      <span className="font-black tracking-widest text-[10px] uppercase">{item.label}</span>
                    </div>
                    <span
  className={cn(
    "font-display text-xl font-bold tracking-tight",
    item.color === "bg-accent-blue"
      ? "text-accent-blue"
      : item.color === "bg-red-500"
      ? "text-red-500"
      : item.color === "bg-yellow-500"
      ? "text-yellow-400"
      : "text-accent-green"
  )}
>{item.score}</span>
                  </div>
                  <div className="w-full bg-white/5 h-2 rounded-full overflow-hidden">
                    <motion.div 
                      initial={{ width: 0 }}
                      animate={{ width: `${(item.score / maxMetric) * 100}%` }}
                      transition={{ duration: 1, delay: index * 0.2 }}
                      className={cn("h-full rounded-full", item.color)} 
                    />
                  </div>
                </div>
              ))}
            </div>

           
         </div>

          {/* Scanner Visual */}
          <div className="col-span-12 md:col-span-6 glass-card rounded-[2.5rem] overflow-hidden group cursor-pointer relative">
            <div className="relative h-72">
              <img 
                className="w-full h-full object-cover opacity-40 grayscale group-hover:grayscale-0 group-hover:scale-105 transition-all duration-1000" 
                src="https://images.unsplash.com/photo-1579353977828-2a4eab540b9a?auto=format&fit=crop&q=80&w=800" 
                alt="Scanner" 
              />
              <div className="absolute inset-0 bg-gradient-to-t from-obsidian via-obsidian/40 to-transparent"></div>
              <div className="absolute bottom-8 left-10 right-10 flex items-center justify-between">
                <h3 className="font-display text-4xl font-bold text-white tracking-tight">Verification Metrics</h3>
                <button
  onClick={downloadAuditReport}
  className="px-5 py-2 bg-accent-blue/10 border border-accent-blue/30 rounded-full flex items-center gap-3 backdrop-blur-md hover:bg-accent-blue/20 transition-all duration-300"
>
  <FileDown className="w-4 h-4 text-accent-blue" />
  <span className="text-accent-blue font-bold text-xs uppercase tracking-wider">
    Export Report
  </span>
</button>
              </div>
            </div>
            <div className="p-10 space-y-8">
	    
	      <div className="grid grid-cols-2 gap-6">
  {[
    {
      label: "FACT RATE",
      value: totalScans
        ? Math.round((factCount / totalScans) * 100)
        : 0,
      color: "text-accent-green"
    },
    {
      label: "CAP RATE",
      value: totalScans
        ? Math.round((capCount / totalScans) * 100)
        : 0,
      color: "text-red-500"
    },
    {
      label: "SUS RATE",
      value: totalScans
        ? Math.round((susCount / totalScans) * 100)
        : 0,
      color: "text-yellow-500"
    },
    {
      label: "AVG TRUST",
      value: averageTrust,
      color: "text-accent-blue"
    }
  ].map((metric, index) => (
    <div
      key={index}
      className="p-6 bg-gradient-to-b from-white/[0.08] to-white/[0.03] rounded-3xl border border-white/5 flex flex-col items-center justify-center min-h-[220px] transition-all duration-300 hover:bg-white/[0.08] hover:scale-105 transition-all duration-500"
    >
      <div className="w-24 h-24 mb-4">
  <CircularProgressbar
    value={metric.value}
    text={`${metric.value}%`}
    styles={buildStyles({
      textColor: "#ffffff",

      pathColor:
        metric.label === "FACT RATE"
          ? "#10B981"
          : metric.label === "CAP RATE"
          ? "#EF4444"
          : metric.label === "SUS RATE"
          ? "#F59E0B"
          : "#3B82F6",

      trailColor: "rgba(255,255,255,0.08)"
    })}
  />
</div>

<div className="text-xs uppercase tracking-widest text-slate-500 font-bold">
  {metric.label}
</div>

<p className="text-[11px] text-slate-400 mt-2">
  {metric.label === "FACT RATE"
    ? "Verified claims"
    : metric.label === "CAP RATE"
    ? "False claims"
    : metric.label === "SUS RATE"
    ? "Uncertain claims"
    : "Archive score"}
</p>
    </div>
  ))}
</div>
              
            </div>
          </div>

          {/* History Tracker */}
          <div className="col-span-12 md:col-span-6 glass-card rounded-[2.5rem] p-10 flex flex-col">
            <h3 className="font-display text-4xl font-bold text-white mb-12 tracking-tight">Verification History</h3>
            <div className="space-y-12 relative flex-grow pt-4">
              <div className="absolute left-[13px] top-6 bottom-4 w-px bg-white/5"></div>
              
              
                {scans
  .sort(
    (a, b) =>
      new Date(b.createdAt).getTime() -
      new Date(a.createdAt).getTime()
  )
  .slice(0, 5)
  .map((item, index) => (
                <div key={index} className="relative pl-12 group cursor-pointer">
                  <div className={cn(
                    "absolute left-0 top-1 w-7 h-7 rounded-full flex items-center justify-center border-4 border-obsidian ring-2 transition-all",
                    item.verdict === 'FACT' ? "bg-accent-green ring-accent-green/20" :
                    item.verdict === 'CAP' ? "bg-red-500 ring-red-500/20 shadow-[0_0_10px_rgba(239,68,68,0.5)]" :
                    "bg-accent-blue animate-pulse ring-accent-blue/20"
                  )}>
                    {
  item.verdict === "FACT" ? (
    <Check className="w-3 h-3 text-obsidian font-bold" />
  ) : item.verdict === "CAP" ? (
    <AlertCircle className="w-3 h-3 text-obsidian font-bold" />
  ) : (
    <HelpCircle className="w-3 h-3 text-obsidian font-bold" />
  )
}
                  </div>
                  <div className="flex justify-between items-start text-left">
                    <div>
                      <p className="font-bold text-lg leading-none transition-colors line-clamp-1 text-white group-hover:text-accent-blue">
  {item.claim}
</p>
                      <p
  className={cn(
    "text-xs mt-2 font-bold tracking-tight uppercase",
    item.verdict === "FACT"
      ? "text-accent-green"
      : item.verdict === "CAP"
      ? "text-red-500"
      : "text-yellow-400"
  )}
>
  {item.verdict}
</p>
                    </div>
                    <span className="text-slate-600 font-bold text-xs">{new Date(item.createdAt).toLocaleDateString()}</span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </motion.div>
    </div>
  );
}
